### PR TITLE
moved clipboard checkbox to preferences gui + basic overlay support

### PR DESCRIPTION
**Pull request by jyannick**
Hi !

I thought it could be nice to save 1 line in the main GUI by moving the "copy to clipboard" checkbox to the preferences. Here is my code, if you are interested. It seems to work fine.
Please note that I am completely new to EDMC, so my code probably needs some critical review before merging.

Thank you for your time.

### CODE REVIEW

**Comment by jyannick** [comment]
Hi again. I just noticed that my git config was not properly set up for github, so the commit did not register with my github account. I fixed it and remade the commit with the new config: this is why I had to force-push. Sorry for that.

**Comment by jyannick** [comment]
Hi ! I've also worked on basic support for the plugin EDMCOverlay. This allows to be notified when reaching waypoints (and thus requiring new plotting) even when EDMC window is minimized.

**Comment by Sognus** [comment]
Unfortunately I have to close PR. There was a big rewrite between versions 1.0 and 1.1. PR was created based on version 1.0. There is no way we will be able resolve so big merge conflict. If you still want to push changes, please base them on latest version or eventually I will do it myself.

**Comment by jyannick** [comment]
No problem, I understand.
I'll try to make time for a rebase on my side, then open another PR.

**Pull request closed without merging**
